# Generated by Django 5.1.1 on 2026-01-08 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="eventfeedback",
            name="student",
            field=models.ForeignKey(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_feedback",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="eventfeedback",
            index=models.Index(
                fields=["event", "rating"], name="reports_eve_event_i_6bcdc5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventfeedback",
            index=models.Index(
                fields=["student", "submitted_at"],
                name="reports_eve_student_e1c7df_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventfeedback",
            unique_together={("event", "student")},
        ),
    ]
