# Generated by Django 5.1.1 on 2026-01-08 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to="users.department",
            ),
        ),
        migrations.AddField(
            model_name="eventcoordinator",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinators",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="eventcoordinator",
            name="faculty",
            field=models.ForeignKey(
                limit_choices_to={"role": "faculty"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinated_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventresource",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resources",
                to="events.event",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="events.venue",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventcoordinator",
            unique_together={("event", "faculty")},
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_date", "status"], name="events_even_event_d_432a97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["department", "status"], name="events_even_departm_5987d3_idx"
            ),
        ),
    ]
