# Generated by Django 5.1.1 on 2025-12-30 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="branch",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cse", "Computer Science & Engineering"),
                    ("ece", "Electronics & Communication"),
                    ("eee", "Electrical & Electronics"),
                    ("me", "Mechanical Engineering"),
                    ("ce", "Civil Engineering"),
                    ("it", "Information Technology"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_google_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StudentEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("cse", "Computer Science & Engineering"),
                            ("ece", "Electronics & Communication"),
                            ("eee", "Electrical & Electronics"),
                            ("me", "Mechanical Engineering"),
                            ("ce", "Civil Engineering"),
                            ("it", "Information Technology"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("roll_number", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Enrollment",
                "verbose_name_plural": "Student Enrollments",
                "ordering": ["-created_at"],
            },
        ),
    ]
