# Generated by Django 5.1.1 on 2026-01-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "verification_method",
                    models.CharField(
                        choices=[
                            ("qr_code", "QR Code"),
                            ("manual", "Manual Entry"),
                            ("biometric", "Biometric"),
                            ("rfid", "RFID Card"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-check_in_time"],
            },
        ),
    ]
